server:
  port: 8762

spring:
  application:
    name: cjs-eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://10.5.0.2:8761/eureka/,http://10.5.0.2:8762/eureka/

logging:
  file: ${spring.application.name}.log
