server:
  port: 8081
  servlet:
    context-path: /commodity
spring:
  application:
    name: cjs-commodity-service
  datasource:
    url: jdbc:mysql://10.5.0.2:3306/test
    username: root
    password: kaixin.com
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://10.5.0.2:8761/eureka/,http://10.5.0.2:8762/eureka/
logging:
  file: ${spring.application.name}.log
